name: Notify

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      NOTIFY_SLUG: ibm-garage-cloud/ibm-garage-iteration-zero

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: ibm-garage-cloud/ibm-garage-iteration-zero
          event-type: new_release
          client-payload: '{"repo": "${{ github.repository }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
